# Generated by Django 4.1.7 on 2023-04-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nombre',
            field=models.CharField(default='usario_sin_nombre', max_length=255),
        ),
    ]
