export const LOGIN_SUCCESS ='LOGIN_SUCCESS';
export const LOGIN_FAIL ='LOGIN_FAIL';
export const LOAD_SUCCESS ='LOAD_SUCCESS';
export const LOAD_FAIL ='LOAD_FAIL';

export const SIGNUP_SUCCESS ='SIGNUP_SUCCESS';
export const  SIGNUP_FAIL ='SIGNUP_FAIL';
export const ACTIVATION_SUCCESS ='ACTIVATION_SUCCESS';
export const  ACTIVATION_FAIL ='ACTIVATION_FAIL';




export const AUTHENTICATED_SUCCESS ='AUTHENTICATED_SUCCESS';
export const AUTHENTICATED_FAIL ='AUTHENTICATED_FAIL';

export const LOGOUT= 'LOGOUT';

export const PASSWORD_RESET_SUCCES= 'PASSWORD_RESET_SUCCES';
export const PASSWORD_RESET_FAIL= 'PASSWORD_RESET_FAIL';
export const PASSWORD_RESET_CONFIRM_SUCCES= 'PASSWORD_RESET_CONFIRM_SUCCES';
export const PASSWORD_RESET_CONFIRM_FAIL= 'PASSWORD_RESET_CONFIRM_FAIL';